- name: "Ensure image manipulation libraries are installed"
  yum: >
    name={{ item }}
    state=present
  with_items:
    - GraphicsMagick
    - GraphicsMagick-devel
    - cairo-devel
    - libjpeg-turbo-devel
  tags:
    - image-manipulation
    - pkgs
